### ISSUE TITLE
nr에 저장된 정수가 매우 클 경우에 대한 처리

### ISSUE THREAD

**Issue by sndjg** [ijsilver/osfall2021#8]
nr에 저장하여 넘겨주는 정수 값이 매우 큰데(예를 들어 1억 이상) 실제로 프로세스의 수는 그보다 훨씬 적을 경우 어떻게 동작해야 하나요? 간단하게 에러를 내는 경우와 실제 프로세스 수에 맞춰 알맞은 값을 반환해주는 경우가 가능할 것 같은데 어느 쪽으로 구현해야 스펙에 맞는지 질문 드립니다. 그리고 이런 경우가 테스트케이스에 포함될 수 있는지도 알고 싶습니다.

추가로, 데모영상의 길이와 발표음성파일의 길이가 합쳐서 4분을 넘지 않아야 하는지, 음성만으로 4분을 넘지 않으면 되는 것인지도 알려주시면 감사하겠습니다.

**Comment by woong97** [comment]
현재 저희 팀이 구현한 코드의 경우, 동작하고 있는 프로세스가 100개인데 nr을 200을 넣어준다면, 100개의 process만이 적절히 출력이 되고 있습니다.
그런데 이걸 넘어서서 너무 큰 nr값을 집어넣을 때 kmalloc에서 메모리 에러가 났을때 에러만 리턴하면 되는 것인지, 아니면 이 경우에도 100개의 프로세스를 출력해줘야 하는 것인지 궁금합니다

**Comment by ijsilver** [comment]
본인이 생각하는 알맞은 정책을 세워서 구현하시고 설명하신다면 크게 문제가 될 부분은 아니라고 생각합니다. 구현과 설명이 적절해야 합니다.

**Comment by ijsilver** [comment]
음성 + 데모까지 합쳐서 4분 이내로 해주시면 감사하겠습니다.
